### ISSUE TITLE
Supply voltage out of recommended specs for 74LVC245 on Rev4

### ISSUE THREAD

**Issue by herraa1** [jabadiagm/MSXgoauld_tn20k#15]
In the published schematic for V4 the supplied voltage for U5 (74LVC245) is 4.7V (5V) and that exceeds the recommended supply voltage range of 1.65V-3.6V as specified in page 5 (section 7.3) of the [SN74LVC245A datasheet](https://www.ti.com/lit/ds/symlink/sn74lvc245a.pdf) by Texas Instruments.

**Comment by jabadiagm** [comment]
Hi,

yes, this is a mistake. U5 is 5V vcc and therefore 74LVC245 is out of valid range. New board revision (testing now) has replaced this chip, among other changes. We hope it will be published soon. 

Thank you for your feedback

Enviado desde mi Alcatel OT511

**Comment by herraa1** [comment]
Thanks. Looking forward to the new board revision.
Maybe a short errata could be added to the readme to discourage people from building the rev4 board as it is known to be flawed.

**Comment by herraa1** [comment]
I've created PR #16 to add the short errata for rev4.

**Comment by stefanobaldo** [comment]
Apologies for reopening this topic, but I’ve ordered some Rev4 boards without noticing the errata. Would replacing the 74LVC245 with the 74HC245 be a possible solution, given that I’ve already ordered the PCBs?

**Comment by stefanobaldo** [comment]
@jabadiagm, any chance you could help me out with this?

**Comment by jabadiagm** [comment]
Sure, if you have an outdated pcb, follow the steps in section "Update from previous hardware":

Replace U1, U2 -> 74HC373, U5 -> 74HC245
Solder a 10K resistor array to data bus lines, pulled up to 5V

**Comment by Chandler-Kluser** [comment]
> Apologies for reopening this topic, but I’ve ordered some Rev4 boards without noticing the errata. Would replacing the 74LVC245 with the 74HC245 be a possible solution, given that I’ve already ordered the PCBs?

There is no problem about using 74LVC245 since they are 5V tolerant. Although it is known this voltage is not recommended by manufactors, in most datasheets you will be able to find that.

I also have made several boards with 74LVC245 with no issues, they are not waste.

**Comment by herraa1** [comment]
The problem is not the input tolerance. The problem is powering them with 5v.

On Sunday, December 15, 2024, 9:04 AM, Chandler Klüser ***@***.***> wrote:





Apologies for reopening this topic, but I’ve ordered some Rev4 boards without noticing the errata. Would replacing the 74LVC245 with the 74HC245 be a possible solution, given that I’ve already ordered the PCBs?


There is no problem about using 74LVC245 since they are 5V tolerant. Although it is known this voltage is not recommended by manufactors, in most datasheets you will be able to find that.

I also have made several boards with 74LVC245 with no issues, they are not waste.

**Comment by Chandler-Kluser** [comment]
Could you, please, read one more time what I have written?

> The problem is not the input tolerance. The problem is powering them with 5v. On Sunday, December 15, 2024, 9:04 AM, Chandler Klüser ***@***.***> wrote: Apologies for reopening this topic, but I’ve ordered some Rev4 boards without noticing the errata. Would replacing the 74LVC245 with the 74HC245 be a possible solution, given that I’ve already ordered the PCBs? There is no problem about using 74LVC245 since they are 5V tolerant. Although it is known this voltage is not recommended by manufactors, in most datasheets you will be able to find that. I also have made several boards with 74LVC245 with no issues, they are not waste. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by Chandler-Kluser** [comment]
@stefanobaldo não há necessidade de comprar outros componentes, se você tiver interesse eu tenho componentes e placas à disposição. Se precisar, pode entrar em contato.

Se você já tiver os 74HC245 à sua disposição, você pode usá-los. Os resistores de 10k são recomendados, mas opcionais.

==========================================================================

@stefanobaldo there is no need to buy other components, if you are interested I have components and boards available. If you need them, you can contact me.

If you already have the 74HC245 at your disposal, you can use them. The 10k resistors are recommended, but optional.

**Comment by herraa1** [comment]
I read the following:

> > Apologies for reopening this topic, but I’ve ordered some Rev4 boards without noticing the errata. Would replacing the 74LVC245 with the 74HC245 be a possible solution, given that I’ve already ordered the PCBs?
> 
> There is no problem about using 74LVC245 since they are 5V tolerant. Although it is known this voltage is not recommended by manufactors, in most datasheets you will be able to find that.
> 
> I also have made several boards with 74LVC245 with no issues, they are not waste.

The OP uses a board that feeds 5V into VCC of U5 which is a 74LVC245 in his revision.

The datasheet of the 74LVC245 clearly states that the recommended VCC is max 3.6V for operating conditions.

![image](https://github.com/user-attachments/assets/7c7463f3-050e-4992-8313-7dc2678850ed)

The datasheet also informs about the absolute maximum ratings, which in the case of VCC is 6.5V.

![image](https://github.com/user-attachments/assets/f3259f3b-420e-4923-97f5-b4746465357b)

You seem to imply that there is no problem in using the 74LVC245 out of the recommended values.
I just wanted to make clear that feeding 5V to VCC of the 74LVC245 is out of the recommended operating conditions as specified in the datasheet provided by the manufacturer. And there is no need to power those chips from 5V specially if you have 3V3 around.

[Absolute maximum ratings vs Recommended operating conditions](https://toshiba.semicon-storage.com/ap-en/semiconductor/knowledge/faq/motor-driver-ics/what-are-the-differences-between-the-absolute-maximum-ratings-and-the-recommended-operating-conditions.html)

Of course, you are free to shoot you in your feet.

**Comment by Chandler-Kluser** [comment]
> I read the following:
> 
> > > Apologies for reopening this topic, but I’ve ordered some Rev4 boards without noticing the errata. Would replacing the 74LVC245 with the 74HC245 be a possible solution, given that I’ve already ordered the PCBs?
> > 
> > There is no problem about using 74LVC245 since they are 5V tolerant. Although it is known this voltage is not recommended by manufactors, in most datasheets you will be able to find that.
> > 
> > I also have made several boards with 74LVC245 with no issues, they are not waste.
> 
> The OP uses a board that feeds 5V into VCC of U5 which is a 74LVC245 in his revision.
> 
> The datasheet of the 74LVC245 clearly states that the recommended VCC is max 3.6V for operating conditions.
> 
> ![image](https://github.com/user-attachments/assets/7c7463f3-050e-4992-8313-7dc2678850ed)
> 
> The datasheet also informs about the absolute maximum ratings, which in the case of VCC is 6.5V.
> 
> ![image](https://github.com/user-attachments/assets/f3259f3b-420e-4923-97f5-b4746465357b)
> 
> You seem to imply that there is no problem in using the 74LVC245 out of the recommended values.
> I just wanted to make clear that feeding 5V to VCC of the 74LVC245 is out of the recommended operating conditions as specified in the datasheet provided by the manufacturer. And there is no need to power those chips from 5V specially if you have 3V3 around.
> 
> [Absolute maximum ratings vs Recommended operating conditions](https://toshiba.semicon-storage.com/ap-en/semiconductor/knowledge/faq/motor-driver-ics/what-are-the-differences-between-the-absolute-maximum-ratings-and-the-recommended-operating-conditions.html)
> 
> Of course, you are free to shoot you in your feet.
> 

The readme has already been updated with useful, sober and polite technical information.

Behaving this way, you can save your comments in your own fork as well as your own board designs.

**Comment by herraa1** [comment]
Woa. I though we were into a more open and constructive conversation.

By the way, I want to say that (not being a native english speaker) I used the expression "shoot you in your feet" figuratively (as in causing you trouble yourself in your goals, like in the [Collins definition](https://www.collinsdictionary.com/dictionary/english/shoot-yourself-in-the-foot)). If this was not understood that way, I want to apologize in advance.

If you believe my arguments are not correct (which may be, we are humans and make mistakes) I would have expected you to point to the flaws in my argumentation so we can all learn from each other.

That said, there's no point in wasting each other's time if that's not the case.
