### ISSUE TITLE
Cartridges not working

### ISSUE THREAD

**Issue by LVina** [jabadiagm/MSXgoauld_tn20k#2]
On some tested MSX1 Models like Philips VG-8020 and Sony HB-75P we are unable to access Cartridges games or peripheral in case of Disk Drive using the CDX-2 Controller.
This is being reviewed already but though would be good to report it here also in the Git.

**Comment by YouInSun** [comment]
Could you let me know if all of the cartridge games are unable to be accessed or if some of the cartridge games are unable to be accessed?
In my cases(FC-80, GoldStar), I could run a 64KB cartridge without a mapper for MSX2 but I could not run a Mega ROM cartridge.

Regards.

**Comment by jabadiagm** [comment]
Hi,
With a stable firmware, most of the msx1 & msx2 cartridges should work. I tried a couple megarom games and run fine (no sound by now). Could you please try firmwares 01-03 and check if there is some difference?

Thank you

Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
The only firmware I could get a fine running with 64KB without mapper(Kralizec Bomb Jack) is the 05_Z80_V9958_bios_mapper_sound_goauld.fs but the others got failure(01 ~ 03 are all shows black screen).
All fs files don’t have success for my mega rom pack.
![image](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/e78b31eb-94e4-41b6-afeb-60a2c43b6b46)

**Comment by YouInSun** [comment]
I've got a successful access of my mega rom pack with a new Tang Nano!
Thanks. :)

**Comment by jabadiagm** [comment]
Great news, thank you for your feedback!

Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Could you let me know how to check my machine has 9958 without game rom pack? For example, in Basic language environment?

**Comment by jabadiagm** [comment]
If your firmware includes bios (02-05) you can test this program in BASIC:

10 color ,0,0 : screen 11

100 for j = 0 to 7
101 for jl = 0 to 7 step 4

110 for k = 0 to 7
111 for kl = 0 to 7 step 2

115 for y = 0 to 15 step 4

120 vpoke n+y+0,(y+0)*16+kl
130 vpoke n+y+1,(y+1)*16+k
140 vpoke n+y+2,(y+2)*16+jl
150 vpoke n+y+3,(y+3)*16+j

200 next y
260 n = n + 512 'n = n + 256 to remove black lines
261 if n >= (256*128) then n = n - (256*128) + 2*16
300 next kl,k,jl,j


1000 goto 1000

https://www.msx.org/forum/msx-talk/software/enhanced-decoding-yjk-images?page=1


Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Thank you for your kind reply. I’ve got the image which the MSX2 can’t get.
Regards.
![image](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/347280cb-7cdf-4757-a1b4-81e076cece5d)

**Comment by jabadiagm** [comment]
Closed as completed
