### ISSUE TITLE
About the version of the Tang Nano 20k

### ISSUE THREAD

**Issue by YouInSun** [jabadiagm/MSXgoauld_tn20k#4]
Could you let me know the version of Tang Nano 20k?
example : please look at the captured picture.

![image](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/b6610f09-cbc8-4677-b42a-314bdb4b59b5)

**Comment by jabadiagm** [comment]
Hi!

all my tangs are v3921 and yet they behave differently with some .fs’s, it would be nice to know why. 

Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Hi,
Thank you for your quick reply.
If I flash the 01_Z80_V9958_goauld.fs, should I use the version 0.6 of Sombrero_MSX_Goa'uld.pdf the slot map is updated ?

Regards.

**Comment by jabadiagm** [comment]
Hello,

firmware works the same with both hardware versions, 0.6 removes two unused signals which caused overheating in U4 when Vcc is much bigger than 5V.  

Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Hello,

I've got the successful operating by your work! (with 05_Z80_V9958_bios_mapper_sound_goauld.fs )
Thank you very much!.

Best Regards.

**Comment by jabadiagm** [comment]
Great news! Thank you for you feedback. 

Enviado desde mi Alcatel OT511
