### ISSUE TITLE
About the remained RAM size

### ISSUE THREAD

**Issue by YouInSun** [jabadiagm/MSXgoauld_tn20k#5]
Hello,
I applied your solution with GoldStar FC-200 and the remained memory shows about 12Kbytes even the original machine gets 24Kbytes.
Could you let me know any possibility shows the size?
Note: I programmed the No. 5 option which has all options(bios sound and mapper)

![IMG_5071](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/0656736d-6903-4e7c-b4cb-bad3621a0db6)

Thank you for your reply in advance.

**Comment by jabadiagm** [comment]
Hi,

I’m sorry, this means firmware is not stable in your tang, different tangs behave differently, still don’t know the reason why. 

Until a fix is found, please try a version without mapper (01, 02, 03). 

Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Hi,

Thank you for your response however I've got a hint to restore remained memory.
When I connected 5v power to the Tang Nano's USB-c port, I've got increased memory. (about 28KBytes)
![IMG_4939](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/2856e6d9-435a-490d-bec0-c73eeb25784c)

For your information!
Regards.

**Comment by YouInSun** [comment]
However, If 4MB mapper is correct, my understanding is that the remained memory would not be 28KB...

**Comment by jabadiagm** [comment]
Hi,

that’s correct. The thing is, Basic can only deal with 28815 bytes maximum, even with a 4 MB mapper. To check total memory, use a tool like testram in MSX-DOS:

https://msxhub.com/TESTRAM

Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Thank you for your explanation!
I will check the tool if I have MSX-DOS.

Regards.
