### ISSUE TITLE
About /M1, /RFSH, /WAIT operations

### ISSUE THREAD

**Issue by YouInSun** [jabadiagm/MSXgoauld_tn20k#7]
Hello,

Thank you for your many help so far and I can see a MSX2+ on my MSX nearly :)
I heard that the most game ROM cartridges don't use specified Z80's control pins.(/M1, /RFSH, /WAIT, etc)
And I think the pins are used by some cartridges which can give and take the signals with Z80 for fetching op code directly.
Could I ask about how I can check whether the pins operate well without a cartridge which can interact Z80 with the pins?
Or, did you checked emulating the pins?

Thank you for your reply in advance.

Best regards.

**Comment by jabadiagm** [comment]
Hi,

Pins m1, rfsh and wait are functional, they are
needed for memory management and timing, even without any cartridge. If you are familiar with gowin software, just enable GAO and plot z80 bus signals.

Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Hi,

Sorry about my inexperience with the application. What I got from signal waveforms were just below. 
It might be good to check when I have a device that can interact with the control signals :)
Thank you for your reply anyway.
![image](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/91e9c758-4e2b-4ae6-9617-845c005fd6f3)

**Comment by jabadiagm** [comment]
You need a modified firmware to run GAO, follow these steps:

Enable gao config file in project
[image: imagen.png]
Build firmware
[image: imagen.png]

Flash new firmware, keep in mind the right name is ao_0.fs
[image: imagen.png]
Start GAO

[image: imagen.png]

Select FT2CH cable
[image: imagen.png]


Start capturing
[image: imagen.png]
Power MSX on

[image: imagen.png]

Start sequence should be captured,

**Comment by YouInSun** [comment]
Hi,

Thank you for your kind explanation and I got a timing chart like below.
![image](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/a4dccc91-4d66-4e19-8c51-45a55e04f4fa)
However, could you let me know how I can trigger /WAIT signal on my MSX?

Best regards.

**Comment by YouInSun** [comment]
Hi,

I've got it another time!
![image](https://github.com/jabadiagm/MSXgoauld_tn20k/assets/19874053/3659c17b-fba9-4c27-b1ad-7bc43731f24b)

**Comment by jabadiagm** [comment]
Hi,

your second capture looks nice. There should be a pulse in WAIT right after a pulse in M1. First capture had something wrong, maybe a loose contact. 

There is an explanation about WAIT signal in MSX here:

https://www.msx.org/forum/msx-talk/development/extra-wait-signal-all-instructions


Enviado desde mi Alcatel OT511

**Comment by YouInSun** [comment]
Thank you for your help!.

Best Regards.
